-- HREI Cash Buyer CRM: public intake plus protected CRM management.
create table if not exists public.cash_buyers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  company_name text,
  email text,
  phone text,
  preferred_contact text not null default 'phone'
    check (preferred_contact in ('phone', 'text', 'email')),
  states text[] not null default array['AL']::text[],
  counties text[] not null default array[]::text[],
  cities_or_zips text,
  strategies text[] not null default array[]::text[],
  property_types text[] not null default array[]::text[],
  occupancy_preferences text[] not null default array[]::text[],
  min_purchase_price numeric,
  max_purchase_price numeric,
  min_arv numeric,
  max_arv numeric,
  max_rehab_budget numeric,
  purchases_last_12_months integer,
  lifetime_purchases integer,
  active_projects integer,
  typical_close_days integer,
  funding_sources text[] not null default array[]::text[],
  proof_of_funds_status text not null default 'available_on_request'
    check (proof_of_funds_status in ('available_on_request', 'requested', 'received', 'not_available')),
  buy_box text,
  buyer_notes text,
  status text not null default 'new'
    check (status in ('new', 'active', 'vetted', 'priority', 'inactive', 'opted_out')),
  internal_notes text,
  email_opt_in boolean not null default false,
  sms_opt_in boolean not null default false,
  contact_opt_out boolean not null default false,
  source text not null default 'Buyer Intake Page',
  last_contacted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cash_buyers_status_idx on public.cash_buyers(status, created_at desc);
create index if not exists cash_buyers_counties_idx on public.cash_buyers using gin(counties);
create index if not exists cash_buyers_strategies_idx on public.cash_buyers using gin(strategies);

alter table public.cash_buyers enable row level security;

drop policy if exists "Public can submit cash buyer intake" on public.cash_buyers;
create policy "Public can submit cash buyer intake"
  on public.cash_buyers for insert to anon, authenticated
  with check (
    status = 'new'
    and source = 'Buyer Intake Page'
    and full_name is not null
  );

drop policy if exists "CRM manages cash buyers" on public.cash_buyers;
create policy "CRM manages cash buyers"
  on public.cash_buyers for all to authenticated
  using (public.is_hrei_owner())
  with check (public.is_hrei_owner());
